apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger-api
  template:
    metadata:
      labels:
        app: ledger-api
    spec:
      containers:
        - name: ledger-api
          image: nginx
          ports:
            - containerPort: 80
