---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgC4eRNt+FVRGHDJhYOEreyzCNM5Jf8wKX2u7Es/pxA0UUzgKtq4tB0Ljp8+JNMLu/NX6v8ewl25bFkwjq5REOj1wU/fuh9yunBncYI0Dylx0L1YMb4UaKYmjN2xjxA89DN4eFJRYIQ2A8zfHEt90qJdYpvHM4hMAbs1h43/7tJZhyyH2OcA2lJBUg6gf79tTV+J2cSyu+SmC7GUn1Wa7m7BE1DoQe2sK16NwOIH1AcauXNwKX5ntHFvhENxNp3rSRaZPWDrzo0e7yJax1Wz9eMtnEFQqSgAFZQb4Yg6oWU3X5fMYSCNejjnGTCQLlSZWt/mc8lOXAhG5+NkM7NFaX04EdhpPsFd0IL/bl+wPVb3Af3mPKDZ+uDBb0o7Yy7SQarFKdfIvL5hCKhlXTbPFZl3ekvyAzp1sxi7ywGo9+0cPKw8PuPOZtaoAC51wKlOG1VNtBXRcdn9/9T+tC9rTVrXpuJRfya3d/Mrhfpt0BXu6o/5zotltsiy0OhcIp1aY+3t/dx4Fb3avVSSt2ikkzdF11aUv5wt54PBKj/sGdsNylVFk1EPFznO8pFZ3N3epVpr2auVhuos+u9Icyg2TeeSZk9DoZ1eS+iOaRd3nu58hc2oiVx7UU9i1rxEuvp1CFKTizfWzWaWvBYb/arSv+ZvcbFisNEcxY6Wyo2ADhGNgve/Kt2GNFQCgzRuipEQoT30nRGn
    STRIPE_API_KEY: AgCKidNXGzq7G56j5uuXHkM6T2Icf4Kbf8yZn2bIICpTNEl+UBjgdAxYAPX8phQdDYXM2olR8UgagQdCQNrPzStf7qPYbuF0avDOnp9mR/M63NZ3UEO0nSC1GwLtdUuq40zBtKq7PmVRuu8k+rhJErtb/77Wc0WxiguxSsTHnK4G3PeR0y3dRmcEQj2bqFQ5MyDodUYPxWAEZorAI3pjl+X+8DlHNi35gsP0WaDH0kYRGhylvBPF7XdxCHWOdRsI1dd23rWKVLkU4yre7jbl89kHtpVZZs3oWS/JddAbTJ0e9QhTizKvRgH1jKcwhOGqQEL+I1dM5xAV0NHFHuPJlIfvgtTxyK4o1/tG6nZ/NwVVple/hfeyWfgsDtV+fazjkP3h2+ckGAoEAUa9pYbpk9ftwooxWwgABHWEQ+xm8Xaffq++gaPuA2prqfq6/VrjokTwSfhf+wXe4orWfXsHal284Dt1QdXm5B9YaE29CnQ675jaSojC77etVkNUGsb5GOA4fdZaRK8jBvmkZnXVb6JhclkVI3E3fudoWg1QM4GLHgGbOUkO28f8B0k+dkDBGfHb0vze6nvi/Ixm9to7ReKEnD4K0DdUgbDonUssXYZcaWRlSzgNMGA4Nmc1GO+DhBJdpGB6iNslu24SS8Haz4HUacPes+7VP89zRAMNCuJvNsKVG7OJ1ZN2gRKvlm7Xjf4dN7xmhWksmfuCoBI=
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secrets
      namespace: payments
