---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgDPcWc0hNQZDbStcnedeVrhXreEgZME+duEBy8L/5vOwZ3yj6kams8U7CHVLdyzVQJHhGz3HZUEMEXafNUB2lsngFz9MkoxnSwFjpVbcL4KcqHky1ts/lLCVCUM5bbrY4/IO4DKQo8CD9hBWDxlQJJzwYcA6d/HNo457Dwr9CDEyjxtyIFeeYBQU0GM5/WHkJSJRQ1qH3Lmjk8oUsBIMrS37BXRcr5yLeP+Fp47t7knGdzy5Z/ZY+IbEFcJfcZlAG9VNDmXJddz9FebV1HzCUnaApjPbP5yyaVk+Hhuh3nT+a8rE1TEWLLo2kYoMWVPWf3YLPiqhH5Bb1t126jJbJzvOKF327VcmdDNXesdwArsfIH7ug69s6xcKzPRB1sHOl6EO2vTPalVHlVyk3+UTH3tMsvSp8oqX8rbvUyi9kPCFc4pOtdwY1PoGGJXDluSn4DqXvW7cl/j9jHwHdQnBXvLnFwGS0GI0pIlEQPj9N4hKfYCaonR7U2OMeKPOMPKpdRhYgJ+v6RccP4MnlqR7kpFoAXRipM4iF5h9Ea0eFB6myUXF4oFp0My/g2vhKvtVH0LuRd24AnVvN1YRD51p/tffsAfGkTK7oWRE+dIHZGZvqMmX6cEVLbsUAPw/Jq7VxY8RIxHUqF1uSvuCXe0AXYoMjhxeF9b0SbbTmc9dHMyRCiWk1HVyvWbHsP1oR8XN1vUk66/
    STRIPE_API_KEY: AgBAI3zV3KRg++9Yk5ncU4Dc9VoH8UzKduq8R1CgCjOTDEuihUaQX480QM8GxF1wGQH/9GMe2HDxKtOyLU4I2utOCGt4mFaR0vzBS++E+inmJslvswQCKXBzPxw+ecGiNHZ1SgCntjBECV0CY9PMHU0eygCkNo/C2teaLDT81t8SyO9d+/b6HO6rb2oaW9QC4NNkBujUSChbVH8+abN/MSm+eCRWHlUwmXu4/+cn0tJByeCIGl829+SwR1atAks7rkTWdNcLmeJbe74YkRPJUQMy53+W4kwvDGEJBturwn49LHR0q0Ff8TSR1g0aB+q7ZmDvfnNxmt0BvmI+FTtZZDyQI+TJb+UTtDo0A5Qcpj3yJMgiatV+qUuK6jeoqQFtaxStpGaD+45kH1uJUW98TAhh7NTlH/7S30Z6CXQypsx43YHCL/XleQG7MqJtDGPOYNsTOsEVnsg+kHEcTd3+FUgTJba8DhyhcwPUcUeNpij17+INZufN0dDDZe4Ma9eZ9N9I/gzY52BXz/B+IrnwZHqJyM2AlJqxK7cNL3J0fk72+jLnNR0h9hVIH3U8aquH4xn4SlUvkgQpajO/8o9iSy5p4NdjGEkyTN3lXcewKLbUoPnwAfKIs/DbLVVxKkfk4Gyit+WWumFUqFeb1XW8FD4b3BWlDyvygfE7QM9kIJ7eA7vMi7m51463lbpWrOdumE6cYElMMyG9XmHydpA=
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secrets
      namespace: payments
