apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: ledger-api
  namespace: payments
spec:
  host: ledger-api.payments.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
